-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [cbor_nopanic]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace cbor_nopanic

/-- [cbor_nopanic::CodecError]
    Source: 'src/lib.rs', lines 21:0-38:1
    Visibility: public -/
@[discriminant isize]
inductive CodecError where
| UnexpectedEnd : CodecError
| TypeMismatch : CodecError
| NonCanonicalLength : CodecError
| IndefiniteLength : CodecError
| DisallowedMajorType : CodecError
| LengthOverflow : CodecError
| WrongLength : CodecError

/-- [cbor_nopanic::{impl core::fmt::Debug for cbor_nopanic::CodecError}::fmt]:
    Source: 'src/lib.rs', lines 20:9-20:14
    Visibility: public -/
def CodecError.Insts.CoreFmtDebug.fmt
  (self : CodecError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | CodecError.UnexpectedEnd =>
    core.fmt.Formatter.write_str f (toStr "UnexpectedEnd")
  | CodecError.TypeMismatch =>
    core.fmt.Formatter.write_str f (toStr "TypeMismatch")
  | CodecError.NonCanonicalLength =>
    core.fmt.Formatter.write_str f (toStr "NonCanonicalLength")
  | CodecError.IndefiniteLength =>
    core.fmt.Formatter.write_str f (toStr "IndefiniteLength")
  | CodecError.DisallowedMajorType =>
    core.fmt.Formatter.write_str f (toStr "DisallowedMajorType")
  | CodecError.LengthOverflow =>
    core.fmt.Formatter.write_str f (toStr "LengthOverflow")
  | CodecError.WrongLength =>
    core.fmt.Formatter.write_str f (toStr "WrongLength")

/-- Trait implementation: [cbor_nopanic::{impl core::fmt::Debug for cbor_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 20:9-20:14 -/
@[reducible]
def CodecError.Insts.CoreFmtDebug : core.fmt.Debug CodecError := {
  fmt := CodecError.Insts.CoreFmtDebug.fmt
}

/-- [cbor_nopanic::{impl core::clone::Clone for cbor_nopanic::CodecError}::clone]:
    Source: 'src/lib.rs', lines 20:16-20:21
    Visibility: public -/
def CodecError.Insts.CoreCloneClone.clone
  (self : CodecError) : Result CodecError := do
  ok self

/-- Trait implementation: [cbor_nopanic::{impl core::clone::Clone for cbor_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 20:16-20:21 -/
@[reducible]
def CodecError.Insts.CoreCloneClone : core.clone.Clone CodecError := {
  clone := CodecError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [cbor_nopanic::{impl core::marker::Copy for cbor_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 20:23-20:27 -/
@[reducible]
def CodecError.Insts.CoreMarkerCopy : core.marker.Copy CodecError := {
  cloneInst := CodecError.Insts.CoreCloneClone
}

/-- Trait implementation: [cbor_nopanic::{impl core::marker::StructuralPartialEq for cbor_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 20:29-20:38 -/
@[reducible]
def CodecError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CodecError := {
}

/-- [cbor_nopanic::{impl core::cmp::PartialEq<cbor_nopanic::CodecError> for cbor_nopanic::CodecError}::eq]:
    Source: 'src/lib.rs', lines 20:29-20:38
    Visibility: public -/
def CodecError.Insts.CoreCmpPartialEqCodecError.eq
  (self : CodecError) (other : CodecError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [cbor_nopanic::{impl core::cmp::PartialEq<cbor_nopanic::CodecError> for cbor_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 20:29-20:38 -/
@[reducible]
def CodecError.Insts.CoreCmpPartialEqCodecError : core.cmp.PartialEq CodecError
  CodecError := {
  eq := CodecError.Insts.CoreCmpPartialEqCodecError.eq
}

/-- [cbor_nopanic::{impl core::cmp::Eq for cbor_nopanic::CodecError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 20:40-20:42
    Visibility: public -/
def CodecError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CodecError) : Result Unit := do
  ok ()

/-- Trait implementation: [cbor_nopanic::{impl core::cmp::Eq for cbor_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 20:40-20:42 -/
@[reducible]
def CodecError.Insts.CoreCmpEq : core.cmp.Eq CodecError := {
  partialEqInst := CodecError.Insts.CoreCmpPartialEqCodecError
  assert_fields_are_eq := CodecError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [cbor_nopanic::MAJOR_UNSIGNED]
    Source: 'src/lib.rs', lines 41:0-41:32 -/
@[global_simps, irreducible] def MAJOR_UNSIGNED : Std.U8 := 0#u8

/-- [cbor_nopanic::MAJOR_BSTR]
    Source: 'src/lib.rs', lines 43:0-43:28 -/
@[global_simps, irreducible] def MAJOR_BSTR : Std.U8 := 64#u8

/-- [cbor_nopanic::MAJOR_MASK]
    Source: 'src/lib.rs', lines 45:0-45:28 -/
@[global_simps, irreducible] def MAJOR_MASK : Std.U8 := 224#u8

/-- [cbor_nopanic::ADDITIONAL_MASK]
    Source: 'src/lib.rs', lines 47:0-47:33 -/
@[global_simps, irreducible] def ADDITIONAL_MASK : Std.U8 := 31#u8

/-- [cbor_nopanic::Reader]
    Source: 'src/lib.rs', lines 55:0-58:1
    Visibility: public -/
structure Reader where
  buf : Slice Std.U8
  pos : Std.Usize

/-- [cbor_nopanic::{cbor_nopanic::Reader<'a>}::new]:
    Source: 'src/lib.rs', lines 63:4-65:5
    Visibility: public -/
def Reader.new (buf : Slice Std.U8) : Result Reader := do
  ok { buf, pos := 0#usize }

/-- [cbor_nopanic::{cbor_nopanic::Reader<'a>}::take]:
    Source: 'src/lib.rs', lines 71:4-85:5 -/
def Reader.take
  (self : Reader) (n : Std.Usize) :
  Result ((core.result.Result (Slice Std.U8) CodecError) × Reader)
  := do
  let o ← lift (Usize.checked_add self.pos n)
  match o with
  | none => ok (core.result.Result.Err CodecError.UnexpectedEnd, self)
  | some end1 =>
    let o1 ←
      core.slice.Slice.get (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)
        self.buf { start := self.pos, «end» := end1 }
    match o1 with
    | none => ok (core.result.Result.Err CodecError.UnexpectedEnd, self)
    | some out => ok (core.result.Result.Ok out, { self with pos := end1 })

/-- [cbor_nopanic::get_u8]:
    Source: 'src/lib.rs', lines 216:0-221:1 -/
def get_u8
  (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (core.result.Result Std.U8 CodecError)
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8) bytes i
  match o with
  | none => ok (core.result.Result.Err CodecError.UnexpectedEnd)
  | some b => ok (core.result.Result.Ok b)

/-- [cbor_nopanic::{cbor_nopanic::Reader<'a>}::read_head]:
    Source: 'src/lib.rs', lines 96:4-158:5 -/
def Reader.read_head
  (self : Reader) (major_base : Std.U8) :
  Result ((core.result.Result Std.U64 CodecError) × Reader)
  := do
  let (r, self1) ← Reader.take self 1#usize
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← get_u8 val 0#usize
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let i ← lift (val1 &&& MAJOR_MASK)
      if i != major_base
      then ok (core.result.Result.Err CodecError.TypeMismatch, self1)
      else
        let additional ← lift (val1 &&& ADDITIONAL_MASK)
        if additional < 24#u8
        then
          let i1 ← lift (core.convert.num.FromU64U8.from additional)
          ok (core.result.Result.Ok i1, self1)
        else
          match additional with
          | 24#uscalar =>
            let (r2, self2) ← Reader.take self1 1#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                if val3 < 24#u8
                then
                  ok (core.result.Result.Err CodecError.NonCanonicalLength,
                    self2)
                else
                  let i1 ← lift (core.convert.num.FromU64U8.from val3)
                  ok (core.result.Result.Ok i1, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | 25#uscalar =>
            let (r2, self2) ← Reader.take self1 2#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let r4 ← get_u8 val2 1#usize
                let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf4 with
                | core.ops.control_flow.ControlFlow.Continue val4 =>
                  let i1 ←
                    lift (core.num.U16.from_be_bytes
                      (Array.make 2#usize [ val3, val4 ]))
                  let value ← lift (core.convert.num.FromU64U16.from i1)
                  let i2 ←
                    lift (core.convert.num.FromU64U8.from core.num.U8.MAX)
                  if value <= i2
                  then
                    ok (core.result.Result.Err CodecError.NonCanonicalLength,
                      self2)
                  else ok (core.result.Result.Ok value, self2)
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r5 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Std.U64 (core.convert.FromSame CodecError) residual
                  ok (r5, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | 26#uscalar =>
            let (r2, self2) ← Reader.take self1 4#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let r4 ← get_u8 val2 1#usize
                let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf4 with
                | core.ops.control_flow.ControlFlow.Continue val4 =>
                  let r5 ← get_u8 val2 2#usize
                  let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                  match cf5 with
                  | core.ops.control_flow.ControlFlow.Continue val5 =>
                    let r6 ← get_u8 val2 3#usize
                    let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                    match cf6 with
                    | core.ops.control_flow.ControlFlow.Continue val6 =>
                      let i1 ←
                        lift (core.num.U32.from_be_bytes
                          (Array.make 4#usize [ val3, val4, val5, val6 ]))
                      let value ← lift (core.convert.num.FromU64U32.from i1)
                      let i2 ←
                        lift (core.convert.num.FromU64U16.from
                          core.num.U16.MAX)
                      if value <= i2
                      then
                        ok (core.result.Result.Err
                          CodecError.NonCanonicalLength, self2)
                      else ok (core.result.Result.Ok value, self2)
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      let r7 ←
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          Std.U64 (core.convert.FromSame CodecError) residual
                      ok (r7, self2)
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    let r6 ←
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        Std.U64 (core.convert.FromSame CodecError) residual
                    ok (r6, self2)
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r5 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Std.U64 (core.convert.FromSame CodecError) residual
                  ok (r5, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | 27#uscalar =>
            let (r2, self2) ← Reader.take self1 8#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let r4 ← get_u8 val2 1#usize
                let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf4 with
                | core.ops.control_flow.ControlFlow.Continue val4 =>
                  let r5 ← get_u8 val2 2#usize
                  let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                  match cf5 with
                  | core.ops.control_flow.ControlFlow.Continue val5 =>
                    let r6 ← get_u8 val2 3#usize
                    let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                    match cf6 with
                    | core.ops.control_flow.ControlFlow.Continue val6 =>
                      let r7 ← get_u8 val2 4#usize
                      let cf7 ← core.result.Result.Insts.CoreOpsTry.branch r7
                      match cf7 with
                      | core.ops.control_flow.ControlFlow.Continue val7 =>
                        let r8 ← get_u8 val2 5#usize
                        let cf8 ←
                          core.result.Result.Insts.CoreOpsTry.branch r8
                        match cf8 with
                        | core.ops.control_flow.ControlFlow.Continue val8 =>
                          let r9 ← get_u8 val2 6#usize
                          let cf9 ←
                            core.result.Result.Insts.CoreOpsTry.branch r9
                          match cf9 with
                          | core.ops.control_flow.ControlFlow.Continue val9 =>
                            let r10 ← get_u8 val2 7#usize
                            let cf10 ←
                              core.result.Result.Insts.CoreOpsTry.branch r10
                            match cf10 with
                            | core.ops.control_flow.ControlFlow.Continue val10
                              =>
                              let value ←
                                lift (core.num.U64.from_be_bytes
                                  (Array.make 8#usize [
                                    val3, val4, val5, val6, val7, val8, val9,
                                    val10
                                    ]))
                              let i1 ←
                                lift (core.convert.num.FromU64U32.from
                                  core.num.U32.MAX)
                              if value <= i1
                              then
                                ok (core.result.Result.Err
                                  CodecError.NonCanonicalLength, self2)
                              else ok (core.result.Result.Ok value, self2)
                            | core.ops.control_flow.ControlFlow.Break residual
                              =>
                              let r11 ←
                                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                  Std.U64 (core.convert.FromSame CodecError)
                                  residual
                              ok (r11, self2)
                          | core.ops.control_flow.ControlFlow.Break residual =>
                            let r10 ←
                              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                Std.U64 (core.convert.FromSame CodecError)
                                residual
                            ok (r10, self2)
                        | core.ops.control_flow.ControlFlow.Break residual =>
                          let r9 ←
                            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                              Std.U64 (core.convert.FromSame CodecError)
                              residual
                          ok (r9, self2)
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        let r8 ←
                          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                            Std.U64 (core.convert.FromSame CodecError) residual
                        ok (r8, self2)
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      let r7 ←
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          Std.U64 (core.convert.FromSame CodecError) residual
                      ok (r7, self2)
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    let r6 ←
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        Std.U64 (core.convert.FromSame CodecError) residual
                    ok (r6, self2)
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r5 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Std.U64 (core.convert.FromSame CodecError) residual
                  ok (r5, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | _ =>
            if 28#u8 <= additional
            then
              if additional <= 30#u8
              then
                ok (core.result.Result.Err CodecError.DisallowedMajorType,
                  self1)
              else
                ok (core.result.Result.Err CodecError.IndefiniteLength, self1)
            else ok (core.result.Result.Err CodecError.IndefiniteLength, self1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r2 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame CodecError) residual
      ok (r2, self1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cbor_nopanic::{cbor_nopanic::Reader<'a>}::read_uint]:
    Source: 'src/lib.rs', lines 166:4-168:5
    Visibility: public -/
def Reader.read_uint
  (self : Reader) :
  Result ((core.result.Result Std.U64 CodecError) × Reader)
  := do
  Reader.read_head self MAJOR_UNSIGNED

/-- [cbor_nopanic::{cbor_nopanic::Reader<'a>}::read_bstr]:
    Source: 'src/lib.rs', lines 177:4-187:5
    Visibility: public -/
def Reader.read_bstr
  (self : Reader) :
  Result ((core.result.Result (Slice Std.U8) CodecError) × Reader)
  := do
  let (r, self1) ← Reader.read_head self MAJOR_BSTR
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← lift (UScalar.cast .U64 core.num.Usize.MAX)
    if val > i
    then ok (core.result.Result.Err CodecError.LengthOverflow, self1)
    else let len ← lift (UScalar.cast .Usize val)
         Reader.take self1 len
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Slice Std.U8) (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cbor_nopanic::{cbor_nopanic::Reader<'a>}::read_bstr_fixed_64]:
    Source: 'src/lib.rs', lines 198:4-207:5
    Visibility: public -/
def Reader.read_bstr_fixed_64
  (self : Reader) :
  Result ((core.result.Result (Array Std.U8 64#usize) CodecError) × Reader)
  := do
  let (r, self1) ← Reader.read_bstr self
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ←
      core.array.TryFromArrayCopySlice.try_from 64#usize core.marker.CopyU8 val
    match r1 with
    | core.result.Result.Ok arr => ok (core.result.Result.Ok arr, self1)
    | core.result.Result.Err _ =>
      ok (core.result.Result.Err CodecError.WrongLength, self1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Array Std.U8 64#usize) (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cbor_nopanic::read_uint]:
    Source: 'src/lib.rs', lines 229:0-233:1
    Visibility: public -/
def read_uint
  (buf : Slice Std.U8) : Result (core.result.Result Std.U64 CodecError) := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_uint reader
  ok r

/-- [cbor_nopanic::read_bstr]:
    Source: 'src/lib.rs', lines 241:0-245:1
    Visibility: public -/
def read_bstr
  (buf : Slice Std.U8) :
  Result (core.result.Result (Slice Std.U8) CodecError)
  := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_bstr reader
  ok r

/-- [cbor_nopanic::read_bstr_fixed_64]:
    Source: 'src/lib.rs', lines 253:0-257:1
    Visibility: public -/
def read_bstr_fixed_64
  (buf : Slice Std.U8) :
  Result (core.result.Result (Array Std.U8 64#usize) CodecError)
  := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_bstr_fixed_64 reader
  ok r

end cbor_nopanic
