-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [cose_parse_nopanic]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace cose_parse_nopanic

/-- [cose_parse_nopanic::CodecError]
    Source: 'src/lib.rs', lines 29:0-54:1
    Visibility: public -/
@[discriminant isize]
inductive CodecError where
| UnexpectedEnd : CodecError
| TypeMismatch : CodecError
| NonCanonicalLength : CodecError
| IndefiniteLength : CodecError
| DisallowedMajorType : CodecError
| LengthOverflow : CodecError
| WrongLength : CodecError
| TrailingBytes : CodecError
| NonCanonicalKeyOrder : CodecError
| InvalidEnumValue : CodecError
| BufferTooSmall : CodecError

/-- [cose_parse_nopanic::{impl core::fmt::Debug for cose_parse_nopanic::CodecError}::fmt]:
    Source: 'src/lib.rs', lines 28:9-28:14
    Visibility: public -/
def CodecError.Insts.CoreFmtDebug.fmt
  (self : CodecError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | CodecError.UnexpectedEnd =>
    core.fmt.Formatter.write_str f (toStr "UnexpectedEnd")
  | CodecError.TypeMismatch =>
    core.fmt.Formatter.write_str f (toStr "TypeMismatch")
  | CodecError.NonCanonicalLength =>
    core.fmt.Formatter.write_str f (toStr "NonCanonicalLength")
  | CodecError.IndefiniteLength =>
    core.fmt.Formatter.write_str f (toStr "IndefiniteLength")
  | CodecError.DisallowedMajorType =>
    core.fmt.Formatter.write_str f (toStr "DisallowedMajorType")
  | CodecError.LengthOverflow =>
    core.fmt.Formatter.write_str f (toStr "LengthOverflow")
  | CodecError.WrongLength =>
    core.fmt.Formatter.write_str f (toStr "WrongLength")
  | CodecError.TrailingBytes =>
    core.fmt.Formatter.write_str f (toStr "TrailingBytes")
  | CodecError.NonCanonicalKeyOrder =>
    core.fmt.Formatter.write_str f (toStr "NonCanonicalKeyOrder")
  | CodecError.InvalidEnumValue =>
    core.fmt.Formatter.write_str f (toStr "InvalidEnumValue")
  | CodecError.BufferTooSmall =>
    core.fmt.Formatter.write_str f (toStr "BufferTooSmall")

/-- Trait implementation: [cose_parse_nopanic::{impl core::fmt::Debug for cose_parse_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 28:9-28:14 -/
@[reducible]
def CodecError.Insts.CoreFmtDebug : core.fmt.Debug CodecError := {
  fmt := CodecError.Insts.CoreFmtDebug.fmt
}

/-- [cose_parse_nopanic::{impl core::clone::Clone for cose_parse_nopanic::CodecError}::clone]:
    Source: 'src/lib.rs', lines 28:16-28:21
    Visibility: public -/
def CodecError.Insts.CoreCloneClone.clone
  (self : CodecError) : Result CodecError := do
  ok self

/-- Trait implementation: [cose_parse_nopanic::{impl core::clone::Clone for cose_parse_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 28:16-28:21 -/
@[reducible]
def CodecError.Insts.CoreCloneClone : core.clone.Clone CodecError := {
  clone := CodecError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [cose_parse_nopanic::{impl core::marker::Copy for cose_parse_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 28:23-28:27 -/
@[reducible]
def CodecError.Insts.CoreMarkerCopy : core.marker.Copy CodecError := {
  cloneInst := CodecError.Insts.CoreCloneClone
}

/-- Trait implementation: [cose_parse_nopanic::{impl core::marker::StructuralPartialEq for cose_parse_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 28:29-28:38 -/
@[reducible]
def CodecError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CodecError := {
}

/-- [cose_parse_nopanic::{impl core::cmp::PartialEq<cose_parse_nopanic::CodecError> for cose_parse_nopanic::CodecError}::eq]:
    Source: 'src/lib.rs', lines 28:29-28:38
    Visibility: public -/
def CodecError.Insts.CoreCmpPartialEqCodecError.eq
  (self : CodecError) (other : CodecError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [cose_parse_nopanic::{impl core::cmp::PartialEq<cose_parse_nopanic::CodecError> for cose_parse_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 28:29-28:38 -/
@[reducible]
def CodecError.Insts.CoreCmpPartialEqCodecError : core.cmp.PartialEq CodecError
  CodecError := {
  eq := CodecError.Insts.CoreCmpPartialEqCodecError.eq
}

/-- [cose_parse_nopanic::{impl core::cmp::Eq for cose_parse_nopanic::CodecError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 28:40-28:42
    Visibility: public -/
def CodecError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CodecError) : Result Unit := do
  ok ()

/-- Trait implementation: [cose_parse_nopanic::{impl core::cmp::Eq for cose_parse_nopanic::CodecError}]
    Source: 'src/lib.rs', lines 28:40-28:42 -/
@[reducible]
def CodecError.Insts.CoreCmpEq : core.cmp.Eq CodecError := {
  partialEqInst := CodecError.Insts.CoreCmpPartialEqCodecError
  assert_fields_are_eq := CodecError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [cose_parse_nopanic::CoseError]
    Source: 'src/lib.rs', lines 65:0-78:1
    Visibility: public -/
@[discriminant isize]
inductive CoseError where
| Codec : CodecError → CoseError
| MalformedEnvelope : CoseError
| NonEmptyUnprotectedHeader : CoseError
| MalformedProtectedHeader : CoseError
| UnsupportedAlgorithm : CoseError
| UnknownTyp : CoseError

/-- [cose_parse_nopanic::{impl core::fmt::Debug for cose_parse_nopanic::CoseError}::fmt]:
    Source: 'src/lib.rs', lines 64:9-64:14
    Visibility: public -/
def CoseError.Insts.CoreFmtDebug.fmt
  (self : CoseError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | CoseError.Codec __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared CodecError.Insts.CoreFmtDebug) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Codec") __self_01
  | CoseError.MalformedEnvelope =>
    core.fmt.Formatter.write_str f (toStr "MalformedEnvelope")
  | CoseError.NonEmptyUnprotectedHeader =>
    core.fmt.Formatter.write_str f (toStr "NonEmptyUnprotectedHeader")
  | CoseError.MalformedProtectedHeader =>
    core.fmt.Formatter.write_str f (toStr "MalformedProtectedHeader")
  | CoseError.UnsupportedAlgorithm =>
    core.fmt.Formatter.write_str f (toStr "UnsupportedAlgorithm")
  | CoseError.UnknownTyp => core.fmt.Formatter.write_str f (toStr "UnknownTyp")

/-- Trait implementation: [cose_parse_nopanic::{impl core::fmt::Debug for cose_parse_nopanic::CoseError}]
    Source: 'src/lib.rs', lines 64:9-64:14 -/
@[reducible]
def CoseError.Insts.CoreFmtDebug : core.fmt.Debug CoseError := {
  fmt := CoseError.Insts.CoreFmtDebug.fmt
}

/-- [cose_parse_nopanic::{impl core::clone::Clone for cose_parse_nopanic::CoseError}::clone]:
    Source: 'src/lib.rs', lines 64:16-64:21
    Visibility: public -/
def CoseError.Insts.CoreCloneClone.clone
  (self : CoseError) : Result CoseError := do
  ok self

/-- Trait implementation: [cose_parse_nopanic::{impl core::clone::Clone for cose_parse_nopanic::CoseError}]
    Source: 'src/lib.rs', lines 64:16-64:21 -/
@[reducible]
def CoseError.Insts.CoreCloneClone : core.clone.Clone CoseError := {
  clone := CoseError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [cose_parse_nopanic::{impl core::marker::Copy for cose_parse_nopanic::CoseError}]
    Source: 'src/lib.rs', lines 64:23-64:27 -/
@[reducible]
def CoseError.Insts.CoreMarkerCopy : core.marker.Copy CoseError := {
  cloneInst := CoseError.Insts.CoreCloneClone
}

/-- Trait implementation: [cose_parse_nopanic::{impl core::marker::StructuralPartialEq for cose_parse_nopanic::CoseError}]
    Source: 'src/lib.rs', lines 64:29-64:38 -/
@[reducible]
def CoseError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CoseError := {
}

/-- [cose_parse_nopanic::{impl core::cmp::PartialEq<cose_parse_nopanic::CoseError> for cose_parse_nopanic::CoseError}::eq]:
    Source: 'src/lib.rs', lines 64:29-64:38
    Visibility: public -/
def CoseError.Insts.CoreCmpPartialEqCoseError.eq
  (self : CoseError) (other : CoseError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | CoseError.Codec __self_0 =>
      match other with
      | CoseError.Codec __arg1_0 =>
        CodecError.Insts.CoreCmpPartialEqCodecError.eq __self_0 __arg1_0
      | CoseError.MalformedEnvelope => ok true
      | CoseError.NonEmptyUnprotectedHeader => ok true
      | CoseError.MalformedProtectedHeader => ok true
      | CoseError.UnsupportedAlgorithm => ok true
      | CoseError.UnknownTyp => ok true
    | CoseError.MalformedEnvelope => ok true
    | CoseError.NonEmptyUnprotectedHeader => ok true
    | CoseError.MalformedProtectedHeader => ok true
    | CoseError.UnsupportedAlgorithm => ok true
    | CoseError.UnknownTyp => ok true
  else ok false

/-- Trait implementation: [cose_parse_nopanic::{impl core::cmp::PartialEq<cose_parse_nopanic::CoseError> for cose_parse_nopanic::CoseError}]
    Source: 'src/lib.rs', lines 64:29-64:38 -/
@[reducible]
def CoseError.Insts.CoreCmpPartialEqCoseError : core.cmp.PartialEq CoseError
  CoseError := {
  eq := CoseError.Insts.CoreCmpPartialEqCoseError.eq
}

/-- [cose_parse_nopanic::{impl core::cmp::Eq for cose_parse_nopanic::CoseError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 64:40-64:42
    Visibility: public -/
def CoseError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CoseError) : Result Unit := do
  ok ()

/-- Trait implementation: [cose_parse_nopanic::{impl core::cmp::Eq for cose_parse_nopanic::CoseError}]
    Source: 'src/lib.rs', lines 64:40-64:42 -/
@[reducible]
def CoseError.Insts.CoreCmpEq : core.cmp.Eq CoseError := {
  partialEqInst := CoseError.Insts.CoreCmpPartialEqCoseError
  assert_fields_are_eq := CoseError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [cose_parse_nopanic::{impl core::convert::From<cose_parse_nopanic::CodecError> for cose_parse_nopanic::CoseError}::from]:
    Source: 'src/lib.rs', lines 84:4-86:5
    Visibility: public -/
def CoseError.Insts.CoreConvertFromCodecError.from
  (error : CodecError) : Result CoseError := do
  ok (CoseError.Codec error)

/-- Trait implementation: [cose_parse_nopanic::{impl core::convert::From<cose_parse_nopanic::CodecError> for cose_parse_nopanic::CoseError}]
    Source: 'src/lib.rs', lines 83:0-87:1 -/
@[reducible]
def CoseError.Insts.CoreConvertFromCodecError : core.convert.From CoseError
  CodecError := {
  «from» := CoseError.Insts.CoreConvertFromCodecError.from
}

/-- [cose_parse_nopanic::MAJOR_UNSIGNED]
    Source: 'src/lib.rs', lines 90:0-90:32 -/
@[global_simps, irreducible] def MAJOR_UNSIGNED : Std.U8 := 0#u8

/-- [cose_parse_nopanic::MAJOR_NEGATIVE]
    Source: 'src/lib.rs', lines 92:0-92:32 -/
@[global_simps, irreducible] def MAJOR_NEGATIVE : Std.U8 := 32#u8

/-- [cose_parse_nopanic::MAJOR_BSTR]
    Source: 'src/lib.rs', lines 94:0-94:28 -/
@[global_simps, irreducible] def MAJOR_BSTR : Std.U8 := 64#u8

/-- [cose_parse_nopanic::MAJOR_TEXT]
    Source: 'src/lib.rs', lines 96:0-96:28 -/
@[global_simps, irreducible] def MAJOR_TEXT : Std.U8 := 96#u8

/-- [cose_parse_nopanic::MAJOR_ARRAY]
    Source: 'src/lib.rs', lines 98:0-98:29 -/
@[global_simps, irreducible] def MAJOR_ARRAY : Std.U8 := 128#u8

/-- [cose_parse_nopanic::MAX_MESSAGE_LEN]
    Source: 'src/lib.rs', lines 103:0-103:40
    Visibility: public -/
@[global_simps, irreducible] def MAX_MESSAGE_LEN : Std.Usize := 4096#usize

/-- [cose_parse_nopanic::MAJOR_MAP]
    Source: 'src/lib.rs', lines 105:0-105:27 -/
@[global_simps, irreducible] def MAJOR_MAP : Std.U8 := 160#u8

/-- [cose_parse_nopanic::MAJOR_MASK]
    Source: 'src/lib.rs', lines 107:0-107:28 -/
@[global_simps, irreducible] def MAJOR_MASK : Std.U8 := 224#u8

/-- [cose_parse_nopanic::ADDITIONAL_MASK]
    Source: 'src/lib.rs', lines 109:0-109:33 -/
@[global_simps, irreducible] def ADDITIONAL_MASK : Std.U8 := 31#u8

/-- [cose_parse_nopanic::ALG_EDDSA_BYTE]
    Source: 'src/lib.rs', lines 111:0-111:49 -/
@[global_simps, irreducible]
def ALG_EDDSA_BYTE : Std.U8 := MAJOR_NEGATIVE ||| 7#u8

/-- [cose_parse_nopanic::Typ]
    Source: 'src/lib.rs', lines 119:0-128:1
    Visibility: public -/
@[discriminant isize]
inductive Typ where
| License : Typ
| Enroll : Typ
| Revoke : Typ
| TrustUpdate : Typ

/-- [cose_parse_nopanic::{impl core::fmt::Debug for cose_parse_nopanic::Typ}::fmt]:
    Source: 'src/lib.rs', lines 118:9-118:14
    Visibility: public -/
def Typ.Insts.CoreFmtDebug.fmt
  (self : Typ) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Typ.License => core.fmt.Formatter.write_str f (toStr "License")
  | Typ.Enroll => core.fmt.Formatter.write_str f (toStr "Enroll")
  | Typ.Revoke => core.fmt.Formatter.write_str f (toStr "Revoke")
  | Typ.TrustUpdate => core.fmt.Formatter.write_str f (toStr "TrustUpdate")

/-- Trait implementation: [cose_parse_nopanic::{impl core::fmt::Debug for cose_parse_nopanic::Typ}]
    Source: 'src/lib.rs', lines 118:9-118:14 -/
@[reducible]
def Typ.Insts.CoreFmtDebug : core.fmt.Debug Typ := {
  fmt := Typ.Insts.CoreFmtDebug.fmt
}

/-- [cose_parse_nopanic::{impl core::clone::Clone for cose_parse_nopanic::Typ}::clone]:
    Source: 'src/lib.rs', lines 118:16-118:21
    Visibility: public -/
def Typ.Insts.CoreCloneClone.clone (self : Typ) : Result Typ := do
  ok self

/-- Trait implementation: [cose_parse_nopanic::{impl core::clone::Clone for cose_parse_nopanic::Typ}]
    Source: 'src/lib.rs', lines 118:16-118:21 -/
@[reducible]
def Typ.Insts.CoreCloneClone : core.clone.Clone Typ := {
  clone := Typ.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [cose_parse_nopanic::{impl core::marker::Copy for cose_parse_nopanic::Typ}]
    Source: 'src/lib.rs', lines 118:23-118:27 -/
@[reducible]
def Typ.Insts.CoreMarkerCopy : core.marker.Copy Typ := {
  cloneInst := Typ.Insts.CoreCloneClone
}

/-- Trait implementation: [cose_parse_nopanic::{impl core::marker::StructuralPartialEq for cose_parse_nopanic::Typ}]
    Source: 'src/lib.rs', lines 118:29-118:38 -/
@[reducible]
def Typ.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Typ := {
}

/-- [cose_parse_nopanic::{impl core::cmp::PartialEq<cose_parse_nopanic::Typ> for cose_parse_nopanic::Typ}::eq]:
    Source: 'src/lib.rs', lines 118:29-118:38
    Visibility: public -/
def Typ.Insts.CoreCmpPartialEqTyp.eq
  (self : Typ) (other : Typ) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [cose_parse_nopanic::{impl core::cmp::PartialEq<cose_parse_nopanic::Typ> for cose_parse_nopanic::Typ}]
    Source: 'src/lib.rs', lines 118:29-118:38 -/
@[reducible]
def Typ.Insts.CoreCmpPartialEqTyp : core.cmp.PartialEq Typ Typ := {
  eq := Typ.Insts.CoreCmpPartialEqTyp.eq
}

/-- [cose_parse_nopanic::{impl core::cmp::Eq for cose_parse_nopanic::Typ}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 118:40-118:42
    Visibility: public -/
def Typ.Insts.CoreCmpEq.assert_fields_are_eq (self : Typ) : Result Unit := do
  ok ()

/-- Trait implementation: [cose_parse_nopanic::{impl core::cmp::Eq for cose_parse_nopanic::Typ}]
    Source: 'src/lib.rs', lines 118:40-118:42 -/
@[reducible]
def Typ.Insts.CoreCmpEq : core.cmp.Eq Typ := {
  partialEqInst := Typ.Insts.CoreCmpPartialEqTyp
  assert_fields_are_eq := Typ.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [cose_parse_nopanic::{cose_parse_nopanic::Typ}::from_u64]:
    Source: 'src/lib.rs', lines 135:4-143:5
    Visibility: public -/
def Typ.from_u64
  (value : Std.U64) : Result (core.result.Result Typ CodecError) := do
  match value with
  | 1#uscalar => ok (core.result.Result.Ok Typ.License)
  | 2#uscalar => ok (core.result.Result.Ok Typ.Enroll)
  | 3#uscalar => ok (core.result.Result.Ok Typ.Revoke)
  | 4#uscalar => ok (core.result.Result.Ok Typ.TrustUpdate)
  | _ => ok (core.result.Result.Err CodecError.InvalidEnumValue)

/-- [cose_parse_nopanic::AAD_LICENSE]
    Source: 'src/lib.rs', lines 147:0-147:51
    Visibility: public -/
@[global_simps, irreducible]
def AAD_LICENSE : Slice Std.U8 :=
  Array.to_slice
    (Array.make 16#usize [
      107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 108#u8, 105#u8, 99#u8,
      101#u8, 110#u8, 115#u8, 101#u8, 47#u8, 118#u8, 49#u8
      ])

/-- [cose_parse_nopanic::AAD_ENROLL]
    Source: 'src/lib.rs', lines 149:0-149:49
    Visibility: public -/
@[global_simps, irreducible]
def AAD_ENROLL : Slice Std.U8 :=
  Array.to_slice
    (Array.make 15#usize [
      107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 101#u8, 110#u8, 114#u8,
      111#u8, 108#u8, 108#u8, 47#u8, 118#u8, 49#u8
      ])

/-- [cose_parse_nopanic::AAD_REVOKE]
    Source: 'src/lib.rs', lines 151:0-151:49
    Visibility: public -/
@[global_simps, irreducible]
def AAD_REVOKE : Slice Std.U8 :=
  Array.to_slice
    (Array.make 15#usize [
      107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 114#u8, 101#u8, 118#u8,
      111#u8, 107#u8, 101#u8, 47#u8, 118#u8, 49#u8
      ])

/-- [cose_parse_nopanic::AAD_TRUST_UPDATE]
    Source: 'src/lib.rs', lines 153:0-153:61
    Visibility: public -/
@[global_simps, irreducible]
def AAD_TRUST_UPDATE : Slice Std.U8 :=
  Array.to_slice
    (Array.make 21#usize [
      107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 116#u8, 114#u8, 117#u8,
      115#u8, 116#u8, 45#u8, 117#u8, 112#u8, 100#u8, 97#u8, 116#u8, 101#u8,
      47#u8, 118#u8, 49#u8
      ])

/-- [cose_parse_nopanic::external_aad]:
    Source: 'src/lib.rs', lines 160:0-167:1
    Visibility: public -/
def external_aad (typ : Typ) : Result (Slice Std.U8) := do
  match typ with
  | Typ.License => ok AAD_LICENSE
  | Typ.Enroll => ok AAD_ENROLL
  | Typ.Revoke => ok AAD_REVOKE
  | Typ.TrustUpdate => ok AAD_TRUST_UPDATE

/-- [cose_parse_nopanic::Reader]
    Source: 'src/lib.rs', lines 175:0-178:1
    Visibility: public -/
structure Reader where
  buf : Slice Std.U8
  pos : Std.Usize

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::new]:
    Source: 'src/lib.rs', lines 183:4-185:5
    Visibility: public -/
def Reader.new (buf : Slice Std.U8) : Result Reader := do
  ok { buf, pos := 0#usize }

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::is_empty]:
    Source: 'src/lib.rs', lines 189:4-191:5
    Visibility: public -/
def Reader.is_empty (self : Reader) : Result Bool := do
  let i := Slice.len self.buf
  ok (self.pos = i)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::finish]:
    Source: 'src/lib.rs', lines 197:4-203:5
    Visibility: public -/
def Reader.finish
  (self : Reader) : Result (core.result.Result Unit CodecError) := do
  let b ← Reader.is_empty self
  if b
  then ok (core.result.Result.Ok ())
  else ok (core.result.Result.Err CodecError.TrailingBytes)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::take]:
    Source: 'src/lib.rs', lines 209:4-223:5 -/
def Reader.take
  (self : Reader) (n : Std.Usize) :
  Result ((core.result.Result (Slice Std.U8) CodecError) × Reader)
  := do
  let o ← lift (Usize.checked_add self.pos n)
  match o with
  | none => ok (core.result.Result.Err CodecError.UnexpectedEnd, self)
  | some end1 =>
    let o1 ←
      core.slice.Slice.get (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)
        self.buf { start := self.pos, «end» := end1 }
    match o1 with
    | none => ok (core.result.Result.Err CodecError.UnexpectedEnd, self)
    | some out => ok (core.result.Result.Ok out, { self with pos := end1 })

/-- [cose_parse_nopanic::get_u8]:
    Source: 'src/lib.rs', lines 426:0-431:1 -/
def get_u8
  (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (core.result.Result Std.U8 CodecError)
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8) bytes i
  match o with
  | none => ok (core.result.Result.Err CodecError.UnexpectedEnd)
  | some b => ok (core.result.Result.Ok b)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_head]:
    Source: 'src/lib.rs', lines 234:4-296:5 -/
def Reader.read_head
  (self : Reader) (major_base : Std.U8) :
  Result ((core.result.Result Std.U64 CodecError) × Reader)
  := do
  let (r, self1) ← Reader.take self 1#usize
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← get_u8 val 0#usize
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let i ← lift (val1 &&& MAJOR_MASK)
      if i != major_base
      then ok (core.result.Result.Err CodecError.TypeMismatch, self1)
      else
        let additional ← lift (val1 &&& ADDITIONAL_MASK)
        if additional < 24#u8
        then
          let i1 ← lift (core.convert.num.FromU64U8.from additional)
          ok (core.result.Result.Ok i1, self1)
        else
          match additional with
          | 24#uscalar =>
            let (r2, self2) ← Reader.take self1 1#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                if val3 < 24#u8
                then
                  ok (core.result.Result.Err CodecError.NonCanonicalLength,
                    self2)
                else
                  let i1 ← lift (core.convert.num.FromU64U8.from val3)
                  ok (core.result.Result.Ok i1, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | 25#uscalar =>
            let (r2, self2) ← Reader.take self1 2#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let r4 ← get_u8 val2 1#usize
                let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf4 with
                | core.ops.control_flow.ControlFlow.Continue val4 =>
                  let i1 ←
                    lift (core.num.U16.from_be_bytes
                      (Array.make 2#usize [ val3, val4 ]))
                  let value ← lift (core.convert.num.FromU64U16.from i1)
                  let i2 ←
                    lift (core.convert.num.FromU64U8.from core.num.U8.MAX)
                  if value <= i2
                  then
                    ok (core.result.Result.Err CodecError.NonCanonicalLength,
                      self2)
                  else ok (core.result.Result.Ok value, self2)
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r5 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Std.U64 (core.convert.FromSame CodecError) residual
                  ok (r5, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | 26#uscalar =>
            let (r2, self2) ← Reader.take self1 4#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let r4 ← get_u8 val2 1#usize
                let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf4 with
                | core.ops.control_flow.ControlFlow.Continue val4 =>
                  let r5 ← get_u8 val2 2#usize
                  let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                  match cf5 with
                  | core.ops.control_flow.ControlFlow.Continue val5 =>
                    let r6 ← get_u8 val2 3#usize
                    let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                    match cf6 with
                    | core.ops.control_flow.ControlFlow.Continue val6 =>
                      let i1 ←
                        lift (core.num.U32.from_be_bytes
                          (Array.make 4#usize [ val3, val4, val5, val6 ]))
                      let value ← lift (core.convert.num.FromU64U32.from i1)
                      let i2 ←
                        lift (core.convert.num.FromU64U16.from
                          core.num.U16.MAX)
                      if value <= i2
                      then
                        ok (core.result.Result.Err
                          CodecError.NonCanonicalLength, self2)
                      else ok (core.result.Result.Ok value, self2)
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      let r7 ←
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          Std.U64 (core.convert.FromSame CodecError) residual
                      ok (r7, self2)
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    let r6 ←
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        Std.U64 (core.convert.FromSame CodecError) residual
                    ok (r6, self2)
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r5 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Std.U64 (core.convert.FromSame CodecError) residual
                  ok (r5, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | 27#uscalar =>
            let (r2, self2) ← Reader.take self1 8#usize
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← get_u8 val2 0#usize
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let r4 ← get_u8 val2 1#usize
                let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf4 with
                | core.ops.control_flow.ControlFlow.Continue val4 =>
                  let r5 ← get_u8 val2 2#usize
                  let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                  match cf5 with
                  | core.ops.control_flow.ControlFlow.Continue val5 =>
                    let r6 ← get_u8 val2 3#usize
                    let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                    match cf6 with
                    | core.ops.control_flow.ControlFlow.Continue val6 =>
                      let r7 ← get_u8 val2 4#usize
                      let cf7 ← core.result.Result.Insts.CoreOpsTry.branch r7
                      match cf7 with
                      | core.ops.control_flow.ControlFlow.Continue val7 =>
                        let r8 ← get_u8 val2 5#usize
                        let cf8 ←
                          core.result.Result.Insts.CoreOpsTry.branch r8
                        match cf8 with
                        | core.ops.control_flow.ControlFlow.Continue val8 =>
                          let r9 ← get_u8 val2 6#usize
                          let cf9 ←
                            core.result.Result.Insts.CoreOpsTry.branch r9
                          match cf9 with
                          | core.ops.control_flow.ControlFlow.Continue val9 =>
                            let r10 ← get_u8 val2 7#usize
                            let cf10 ←
                              core.result.Result.Insts.CoreOpsTry.branch r10
                            match cf10 with
                            | core.ops.control_flow.ControlFlow.Continue val10
                              =>
                              let value ←
                                lift (core.num.U64.from_be_bytes
                                  (Array.make 8#usize [
                                    val3, val4, val5, val6, val7, val8, val9,
                                    val10
                                    ]))
                              let i1 ←
                                lift (core.convert.num.FromU64U32.from
                                  core.num.U32.MAX)
                              if value <= i1
                              then
                                ok (core.result.Result.Err
                                  CodecError.NonCanonicalLength, self2)
                              else ok (core.result.Result.Ok value, self2)
                            | core.ops.control_flow.ControlFlow.Break residual
                              =>
                              let r11 ←
                                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                  Std.U64 (core.convert.FromSame CodecError)
                                  residual
                              ok (r11, self2)
                          | core.ops.control_flow.ControlFlow.Break residual =>
                            let r10 ←
                              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                Std.U64 (core.convert.FromSame CodecError)
                                residual
                            ok (r10, self2)
                        | core.ops.control_flow.ControlFlow.Break residual =>
                          let r9 ←
                            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                              Std.U64 (core.convert.FromSame CodecError)
                              residual
                          ok (r9, self2)
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        let r8 ←
                          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                            Std.U64 (core.convert.FromSame CodecError) residual
                        ok (r8, self2)
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      let r7 ←
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          Std.U64 (core.convert.FromSame CodecError) residual
                      ok (r7, self2)
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    let r6 ←
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        Std.U64 (core.convert.FromSame CodecError) residual
                    ok (r6, self2)
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r5 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Std.U64 (core.convert.FromSame CodecError) residual
                  ok (r5, self2)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r4 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Std.U64 (core.convert.FromSame CodecError) residual
                ok (r4, self2)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r3 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Std.U64 (core.convert.FromSame CodecError) residual
              ok (r3, self2)
          | _ =>
            if 28#u8 <= additional
            then
              if additional <= 30#u8
              then
                ok (core.result.Result.Err CodecError.DisallowedMajorType,
                  self1)
              else
                ok (core.result.Result.Err CodecError.IndefiniteLength, self1)
            else ok (core.result.Result.Err CodecError.IndefiniteLength, self1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r2 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame CodecError) residual
      ok (r2, self1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_uint]:
    Source: 'src/lib.rs', lines 304:4-306:5
    Visibility: public -/
def Reader.read_uint
  (self : Reader) :
  Result ((core.result.Result Std.U64 CodecError) × Reader)
  := do
  Reader.read_head self MAJOR_UNSIGNED

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_bstr]:
    Source: 'src/lib.rs', lines 315:4-325:5
    Visibility: public -/
def Reader.read_bstr
  (self : Reader) :
  Result ((core.result.Result (Slice Std.U8) CodecError) × Reader)
  := do
  let (r, self1) ← Reader.read_head self MAJOR_BSTR
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← lift (UScalar.cast .U64 core.num.Usize.MAX)
    if val > i
    then ok (core.result.Result.Err CodecError.LengthOverflow, self1)
    else let len ← lift (UScalar.cast .Usize val)
         Reader.take self1 len
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Slice Std.U8) (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_bstr_fixed_64]:
    Source: 'src/lib.rs', lines 336:4-345:5
    Visibility: public -/
def Reader.read_bstr_fixed_64
  (self : Reader) :
  Result ((core.result.Result (Array Std.U8 64#usize) CodecError) × Reader)
  := do
  let (r, self1) ← Reader.read_bstr self
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ←
      core.array.TryFromArrayCopySlice.try_from 64#usize core.marker.CopyU8 val
    match r1 with
    | core.result.Result.Ok arr => ok (core.result.Result.Ok arr, self1)
    | core.result.Result.Err _ =>
      ok (core.result.Result.Err CodecError.WrongLength, self1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Array Std.U8 64#usize) (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_bstr_fixed_16]:
    Source: 'src/lib.rs', lines 356:4-365:5
    Visibility: public -/
def Reader.read_bstr_fixed_16
  (self : Reader) :
  Result ((core.result.Result (Array Std.U8 16#usize) CodecError) × Reader)
  := do
  let (r, self1) ← Reader.read_bstr self
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ←
      core.array.TryFromArrayCopySlice.try_from 16#usize core.marker.CopyU8 val
    match r1 with
    | core.result.Result.Ok arr => ok (core.result.Result.Ok arr, self1)
    | core.result.Result.Err _ =>
      ok (core.result.Result.Err CodecError.WrongLength, self1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (Array Std.U8 16#usize) (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_array_header]:
    Source: 'src/lib.rs', lines 371:4-373:5
    Visibility: public -/
def Reader.read_array_header
  (self : Reader) :
  Result ((core.result.Result Std.U64 CodecError) × Reader)
  := do
  Reader.read_head self MAJOR_ARRAY

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_map_header]:
    Source: 'src/lib.rs', lines 379:4-381:5
    Visibility: public -/
def Reader.read_map_header
  (self : Reader) :
  Result ((core.result.Result Std.U64 CodecError) × Reader)
  := do
  Reader.read_head self MAJOR_MAP

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::read_fixed_byte]:
    Source: 'src/lib.rs', lines 388:4-397:5
    Visibility: public -/
def Reader.read_fixed_byte
  (self : Reader) (expected : Std.U8) :
  Result ((core.result.Result Unit CodecError) × Reader)
  := do
  let (r, self1) ← Reader.take self 1#usize
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← get_u8 val 0#usize
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      if val1 = expected
      then ok (core.result.Result.Ok (), self1)
      else ok (core.result.Result.Err CodecError.TypeMismatch, self1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r2 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Unit (core.convert.FromSame CodecError) residual
      ok (r2, self1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Unit (core.convert.FromSame CodecError) residual
    ok (r1, self1)

/-- [cose_parse_nopanic::{cose_parse_nopanic::Reader<'a>}::next_map_key]:
    Source: 'src/lib.rs', lines 405:4-417:5
    Visibility: public -/
def Reader.next_map_key
  (self : Reader) (last_key : Option Std.U64) :
  Result ((core.result.Result Std.U64 CodecError) × Reader × (Option
    Std.U64))
  := do
  let (r, self1) ← Reader.read_uint self
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    match last_key with
    | none => ok (core.result.Result.Ok val, self1, some val)
    | some last =>
      if val <= last
      then
        ok (core.result.Result.Err CodecError.NonCanonicalKeyOrder, self1,
          last_key)
      else ok (core.result.Result.Ok val, self1, some val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame CodecError) residual
    ok (r1, self1, last_key)

/-- [cose_parse_nopanic::read_uint]:
    Source: 'src/lib.rs', lines 439:0-443:1
    Visibility: public -/
def read_uint
  (buf : Slice Std.U8) : Result (core.result.Result Std.U64 CodecError) := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_uint reader
  ok r

/-- [cose_parse_nopanic::read_bstr]:
    Source: 'src/lib.rs', lines 451:0-455:1
    Visibility: public -/
def read_bstr
  (buf : Slice Std.U8) :
  Result (core.result.Result (Slice Std.U8) CodecError)
  := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_bstr reader
  ok r

/-- [cose_parse_nopanic::read_bstr_fixed_64]:
    Source: 'src/lib.rs', lines 463:0-467:1
    Visibility: public -/
def read_bstr_fixed_64
  (buf : Slice Std.U8) :
  Result (core.result.Result (Array Std.U8 64#usize) CodecError)
  := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_bstr_fixed_64 reader
  ok r

/-- [cose_parse_nopanic::read_array_header]:
    Source: 'src/lib.rs', lines 475:0-479:1
    Visibility: public -/
def read_array_header
  (buf : Slice Std.U8) : Result (core.result.Result Std.U64 CodecError) := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_array_header reader
  ok r

/-- [cose_parse_nopanic::read_map_header]:
    Source: 'src/lib.rs', lines 487:0-491:1
    Visibility: public -/
def read_map_header
  (buf : Slice Std.U8) : Result (core.result.Result Std.U64 CodecError) := do
  let reader ← Reader.new buf
  let (r, _) ← Reader.read_map_header reader
  ok r

/-- [cose_parse_nopanic::Envelope]
    Source: 'src/lib.rs', lines 499:0-506:1
    Visibility: public -/
structure Envelope where
  «protected» : Slice Std.U8
  payload : Slice Std.U8
  signature : Array Std.U8 64#usize

/-- [cose_parse_nopanic::read_sign1_envelope]:
    Source: 'src/lib.rs', lines 527:0-546:1
    Visibility: public -/
def read_sign1_envelope
  (buf : Slice Std.U8) : Result (core.result.Result Envelope CoseError) := do
  let reader ← Reader.new buf
  let (r, reader1) ← Reader.read_array_header reader
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val != 4#u64
    then ok (core.result.Result.Err CoseError.MalformedEnvelope)
    else
      let (r1, reader2) ← Reader.read_bstr reader1
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (r2, reader3) ← Reader.read_map_header reader2
        let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          if val2 != 0#u64
          then ok (core.result.Result.Err CoseError.NonEmptyUnprotectedHeader)
          else
            let (r3, reader4) ← Reader.read_bstr reader3
            let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
            match cf3 with
            | core.ops.control_flow.ControlFlow.Continue val3 =>
              let (r4, reader5) ← Reader.read_bstr_fixed_64 reader4
              let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
              match cf4 with
              | core.ops.control_flow.ControlFlow.Continue val4 =>
                let r5 ← Reader.finish reader5
                let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                match cf5 with
                | core.ops.control_flow.ControlFlow.Continue _ =>
                  ok (core.result.Result.Ok
                    { «protected» := val1, payload := val3, signature := val4
                    })
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Envelope CoseError.Insts.CoreConvertFromCodecError residual
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Envelope CoseError.Insts.CoreConvertFromCodecError residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Envelope CoseError.Insts.CoreConvertFromCodecError residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Envelope CoseError.Insts.CoreConvertFromCodecError residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Envelope CoseError.Insts.CoreConvertFromCodecError residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Envelope CoseError.Insts.CoreConvertFromCodecError residual

/-- [cose_parse_nopanic::decode_protected_header]:
    Source: 'src/lib.rs', lines 560:0-599:1
    Visibility: public -/
def decode_protected_header
  (bytes : Slice Std.U8) :
  Result (core.result.Result ((Array Std.U8 16#usize) × Typ) CoseError)
  := do
  let reader ← Reader.new bytes
  let (r, reader1) ← Reader.read_map_header reader
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val != 3#u64
    then ok (core.result.Result.Err CoseError.MalformedProtectedHeader)
    else
      let (r1, reader2, last_key) ← Reader.next_map_key reader1 none
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        if val1 != 1#u64
        then ok (core.result.Result.Err CoseError.MalformedProtectedHeader)
        else
          let (r2, reader3) ← Reader.read_fixed_byte reader2 ALG_EDDSA_BYTE
          match r2 with
          | core.result.Result.Ok _ =>
            let (r3, reader4, last_key1) ←
              Reader.next_map_key reader3 last_key
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r3
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              if val2 != 4#u64
              then
                ok (core.result.Result.Err CoseError.MalformedProtectedHeader)
              else
                let (r4, reader5) ← Reader.read_bstr_fixed_16 reader4
                let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf3 with
                | core.ops.control_flow.ControlFlow.Continue val3 =>
                  let (r5, reader6, _) ←
                    Reader.next_map_key reader5 last_key1
                  let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r5
                  match cf4 with
                  | core.ops.control_flow.ControlFlow.Continue val4 =>
                    if val4 != 100#u64
                    then
                      ok (core.result.Result.Err
                        CoseError.MalformedProtectedHeader)
                    else
                      let (r6, reader7) ← Reader.read_uint reader6
                      let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r6
                      match cf5 with
                      | core.ops.control_flow.ControlFlow.Continue val5 =>
                        let r7 ← Typ.from_u64 val5
                        match r7 with
                        | core.result.Result.Ok typ =>
                          let r8 ← Reader.finish reader7
                          let cf6 ←
                            core.result.Result.Insts.CoreOpsTry.branch r8
                          match cf6 with
                          | core.ops.control_flow.ControlFlow.Continue _ =>
                            ok (core.result.Result.Ok (val3, typ))
                          | core.ops.control_flow.ControlFlow.Break residual =>
                            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                              ((Array Std.U8 16#usize) × Typ)
                              CoseError.Insts.CoreConvertFromCodecError
                              residual
                        | core.result.Result.Err _ =>
                          ok (core.result.Result.Err CoseError.UnknownTyp)
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          ((Array Std.U8 16#usize) × Typ)
                          CoseError.Insts.CoreConvertFromCodecError residual
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      ((Array Std.U8 16#usize) × Typ)
                      CoseError.Insts.CoreConvertFromCodecError residual
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    ((Array Std.U8 16#usize) × Typ)
                    CoseError.Insts.CoreConvertFromCodecError residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                ((Array Std.U8 16#usize) × Typ)
                CoseError.Insts.CoreConvertFromCodecError residual
          | core.result.Result.Err _ =>
            ok (core.result.Result.Err CoseError.UnsupportedAlgorithm)
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          ((Array Std.U8 16#usize) × Typ)
          CoseError.Insts.CoreConvertFromCodecError residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      ((Array Std.U8 16#usize) × Typ)
      CoseError.Insts.CoreConvertFromCodecError residual

/-- [cose_parse_nopanic::SliceSink]
    Source: 'src/lib.rs', lines 606:0-609:1 -/
structure SliceSink where
  buf : Array Std.U8 4096#usize
  len : Std.Usize

/-- [cose_parse_nopanic::{cose_parse_nopanic::SliceSink}::new]:
    Source: 'src/lib.rs', lines 614:4-619:5 -/
def SliceSink.new : Result SliceSink := do
  let a := Array.repeat 4096#usize 0#u8
  ok { buf := a, len := 0#usize }

/-- [cose_parse_nopanic::{cose_parse_nopanic::SliceSink}::len]:
    Source: 'src/lib.rs', lines 622:4-624:5 -/
def SliceSink.impl.len (self : SliceSink) : Result Std.Usize := do
  ok self.len

/-- [cose_parse_nopanic::{cose_parse_nopanic::SliceSink}::write_bytes]:
    Source: 'src/lib.rs', lines 630:4-653:5 -/
def SliceSink.write_bytes
  (self : SliceSink) (bytes : Slice Std.U8) :
  Result ((core.result.Result Unit CodecError) × SliceSink)
  := do
  let i := Slice.len bytes
  let o ← lift (Usize.checked_add self.len i)
  match o with
  | none => ok (core.result.Result.Err CodecError.BufferTooSmall, self)
  | some end1 =>
    let (s, to_slice_mut_back) ← lift (Array.to_slice_mut self.buf)
    let (o1, get_mut_back) ←
      core.slice.Slice.get_mut (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) s { start := self.len, «end» := end1 }
    match o1 with
    | none =>
      let s1 := get_mut_back none
      let a := to_slice_mut_back s1
      ok (core.result.Result.Err CodecError.BufferTooSmall,
        { self with buf := a })
    | some dest =>
      let i1 := Slice.len dest
      let i2 := Slice.len bytes
      if i1 != i2
      then
        let s1 := get_mut_back o1
        let a := to_slice_mut_back s1
        ok (core.result.Result.Err CodecError.BufferTooSmall,
          { self with buf := a })
      else
        let dest1 ←
          core.slice.Slice.copy_from_slice core.marker.CopyU8 dest bytes
        let s1 := get_mut_back (some dest1)
        let a := to_slice_mut_back s1
        ok (core.result.Result.Ok (), { buf := a, len := end1 })

/-- [cose_parse_nopanic::be_byte]:
    Source: 'src/lib.rs', lines 661:0-666:1 -/
def be_byte
  (be : Array Std.U8 8#usize) (i : Std.Usize) :
  Result (core.result.Result Std.U8 CodecError)
  := do
  let s ← lift (Array.to_slice be)
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8) s i
  match o with
  | none => ok (core.result.Result.Err CodecError.BufferTooSmall)
  | some b => ok (core.result.Result.Ok b)

/-- [cose_parse_nopanic::write_head]:
    Source: 'src/lib.rs', lines 674:0-713:1 -/
def write_head
  (sink : SliceSink) (major_base : Std.U8) (arg : Std.U64) :
  Result ((core.result.Result Unit CodecError) × SliceSink)
  := do
  if arg < 24#u64
  then
    let small ← lift (UScalar.cast .U8 arg)
    let i ← lift (major_base ||| small)
    let s ← lift (Array.to_slice (Array.make 1#usize [ i ]))
    SliceSink.write_bytes sink s
  else
    let be ← lift (core.num.U64.to_be_bytes arg)
    let i ← lift (core.convert.num.FromU64U8.from core.num.U8.MAX)
    if arg <= i
    then
      let r ← be_byte be 7#usize
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let i1 ← lift (major_base ||| 24#u8)
        let s ← lift (Array.to_slice (Array.make 2#usize [ i1, val ]))
        SliceSink.write_bytes sink s
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r1 ←
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Unit (core.convert.FromSame CodecError) residual
        ok (r1, sink)
    else
      let i1 ← lift (core.convert.num.FromU64U16.from core.num.U16.MAX)
      if arg <= i1
      then
        let i2 ← lift (major_base ||| 25#u8)
        let r ← be_byte be 6#usize
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let r1 ← be_byte be 7#usize
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue val1 =>
            let s ←
              lift (Array.to_slice (Array.make 3#usize [ i2, val, val1 ]))
            SliceSink.write_bytes sink s
          | core.ops.control_flow.ControlFlow.Break residual =>
            let r2 ←
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Unit (core.convert.FromSame CodecError) residual
            ok (r2, sink)
        | core.ops.control_flow.ControlFlow.Break residual =>
          let r1 ←
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Unit (core.convert.FromSame CodecError) residual
          ok (r1, sink)
      else
        let i2 ← lift (core.convert.num.FromU64U32.from core.num.U32.MAX)
        if arg <= i2
        then
          let i3 ← lift (major_base ||| 26#u8)
          let r ← be_byte be 4#usize
          let cf ← core.result.Result.Insts.CoreOpsTry.branch r
          match cf with
          | core.ops.control_flow.ControlFlow.Continue val =>
            let r1 ← be_byte be 5#usize
            let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
            match cf1 with
            | core.ops.control_flow.ControlFlow.Continue val1 =>
              let r2 ← be_byte be 6#usize
              let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
              match cf2 with
              | core.ops.control_flow.ControlFlow.Continue val2 =>
                let r3 ← be_byte be 7#usize
                let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
                match cf3 with
                | core.ops.control_flow.ControlFlow.Continue val3 =>
                  let s ←
                    lift (Array.to_slice
                      (Array.make 5#usize [ i3, val, val1, val2, val3 ]))
                  SliceSink.write_bytes sink s
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r4 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Unit (core.convert.FromSame CodecError) residual
                  ok (r4, sink)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r3 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Unit (core.convert.FromSame CodecError) residual
                ok (r3, sink)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r2 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Unit (core.convert.FromSame CodecError) residual
              ok (r2, sink)
          | core.ops.control_flow.ControlFlow.Break residual =>
            let r1 ←
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Unit (core.convert.FromSame CodecError) residual
            ok (r1, sink)
        else
          let i3 ← lift (major_base ||| 27#u8)
          let r ← be_byte be 0#usize
          let cf ← core.result.Result.Insts.CoreOpsTry.branch r
          match cf with
          | core.ops.control_flow.ControlFlow.Continue val =>
            let r1 ← be_byte be 1#usize
            let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
            match cf1 with
            | core.ops.control_flow.ControlFlow.Continue val1 =>
              let r2 ← be_byte be 2#usize
              let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
              match cf2 with
              | core.ops.control_flow.ControlFlow.Continue val2 =>
                let r3 ← be_byte be 3#usize
                let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
                match cf3 with
                | core.ops.control_flow.ControlFlow.Continue val3 =>
                  let r4 ← be_byte be 4#usize
                  let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                  match cf4 with
                  | core.ops.control_flow.ControlFlow.Continue val4 =>
                    let r5 ← be_byte be 5#usize
                    let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                    match cf5 with
                    | core.ops.control_flow.ControlFlow.Continue val5 =>
                      let r6 ← be_byte be 6#usize
                      let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                      match cf6 with
                      | core.ops.control_flow.ControlFlow.Continue val6 =>
                        let r7 ← be_byte be 7#usize
                        let cf7 ←
                          core.result.Result.Insts.CoreOpsTry.branch r7
                        match cf7 with
                        | core.ops.control_flow.ControlFlow.Continue val7 =>
                          let s ←
                            lift (Array.to_slice
                              (Array.make 9#usize [
                                i3, val, val1, val2, val3, val4, val5, val6,
                                val7
                                ]))
                          SliceSink.write_bytes sink s
                        | core.ops.control_flow.ControlFlow.Break residual =>
                          let r8 ←
                            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                              Unit (core.convert.FromSame CodecError) residual
                          ok (r8, sink)
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        let r7 ←
                          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                            Unit (core.convert.FromSame CodecError) residual
                        ok (r7, sink)
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      let r6 ←
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          Unit (core.convert.FromSame CodecError) residual
                      ok (r6, sink)
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    let r5 ←
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        Unit (core.convert.FromSame CodecError) residual
                    ok (r5, sink)
                | core.ops.control_flow.ControlFlow.Break residual =>
                  let r4 ←
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      Unit (core.convert.FromSame CodecError) residual
                  ok (r4, sink)
              | core.ops.control_flow.ControlFlow.Break residual =>
                let r3 ←
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    Unit (core.convert.FromSame CodecError) residual
                ok (r3, sink)
            | core.ops.control_flow.ControlFlow.Break residual =>
              let r2 ←
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Unit (core.convert.FromSame CodecError) residual
              ok (r2, sink)
          | core.ops.control_flow.ControlFlow.Break residual =>
            let r1 ←
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                Unit (core.convert.FromSame CodecError) residual
            ok (r1, sink)

/-- [cose_parse_nopanic::write_bstr]:
    Source: 'src/lib.rs', lines 721:0-728:1 -/
def write_bstr
  (sink : SliceSink) (bytes : Slice Std.U8) :
  Result ((core.result.Result Unit CodecError) × SliceSink)
  := do
  let i := Slice.len bytes
  let len ← lift (UScalar.cast .U64 i)
  let (r, sink1) ← write_head sink MAJOR_BSTR len
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    SliceSink.write_bytes sink1 bytes
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Unit (core.convert.FromSame CodecError) residual
    ok (r1, sink1)

/-- [cose_parse_nopanic::write_text]:
    Source: 'src/lib.rs', lines 738:0-743:1 -/
def write_text
  (sink : SliceSink) (text : Slice Std.U8) :
  Result ((core.result.Result Unit CodecError) × SliceSink)
  := do
  let i := Slice.len text
  let len ← lift (UScalar.cast .U64 i)
  let (r, sink1) ← write_head sink MAJOR_TEXT len
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    SliceSink.write_bytes sink1 text
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Unit (core.convert.FromSame CodecError) residual
    ok (r1, sink1)

/-- [cose_parse_nopanic::write_array_header]:
    Source: 'src/lib.rs', lines 751:0-753:1 -/
def write_array_header
  (sink : SliceSink) (len : Std.U64) :
  Result ((core.result.Result Unit CodecError) × SliceSink)
  := do
  write_head sink MAJOR_ARRAY len

/-- [cose_parse_nopanic::SigStructure]
    Source: 'src/lib.rs', lines 760:0-765:1
    Visibility: public -/
structure SigStructure where
  buf : Array Std.U8 4096#usize
  len : Std.Usize

/-- [cose_parse_nopanic::build_sig_structure]:
    Source: 'src/lib.rs', lines 775:0-803:1
    Visibility: public -/
def build_sig_structure
  (typ : Typ) (protected1 : Slice Std.U8) (payload : Slice Std.U8) :
  Result (core.result.Result SigStructure CoseError)
  := do
  let sink ← SliceSink.new
  let (r, sink1) ← write_array_header sink 4#u64
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let s ←
      lift (Array.to_slice
        (Array.make 10#usize [
          83#u8, 105#u8, 103#u8, 110#u8, 97#u8, 116#u8, 117#u8, 114#u8, 101#u8,
          49#u8
          ]))
    let (r1, sink2) ← write_text sink1 s
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      let (r2, sink3) ← write_bstr sink2 protected1
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        match typ with
        | Typ.License =>
          let s1 ←
            lift (Array.to_slice
              (Array.make 16#usize [
                107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 108#u8, 105#u8,
                99#u8, 101#u8, 110#u8, 115#u8, 101#u8, 47#u8, 118#u8, 49#u8
                ]))
          let (r3, sink4) ← write_bstr sink3 s1
          let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            let (r4, sink5) ← write_bstr sink4 payload
            let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
            match cf4 with
            | core.ops.control_flow.ControlFlow.Continue _ =>
              let written_len ← SliceSink.impl.len sink5
              if written_len > MAX_MESSAGE_LEN
              then
                ok (core.result.Result.Err (CoseError.Codec
                  CodecError.BufferTooSmall))
              else
                ok (core.result.Result.Ok
                  { buf := sink5.buf, len := written_len })
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                SigStructure CoseError.Insts.CoreConvertFromCodecError residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              SigStructure CoseError.Insts.CoreConvertFromCodecError residual
        | Typ.Enroll =>
          let s1 ←
            lift (Array.to_slice
              (Array.make 15#usize [
                107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 101#u8, 110#u8,
                114#u8, 111#u8, 108#u8, 108#u8, 47#u8, 118#u8, 49#u8
                ]))
          let (r3, sink4) ← write_bstr sink3 s1
          let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            let (r4, sink5) ← write_bstr sink4 payload
            let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
            match cf4 with
            | core.ops.control_flow.ControlFlow.Continue _ =>
              let written_len ← SliceSink.impl.len sink5
              if written_len > MAX_MESSAGE_LEN
              then
                ok (core.result.Result.Err (CoseError.Codec
                  CodecError.BufferTooSmall))
              else
                ok (core.result.Result.Ok
                  { buf := sink5.buf, len := written_len })
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                SigStructure CoseError.Insts.CoreConvertFromCodecError residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              SigStructure CoseError.Insts.CoreConvertFromCodecError residual
        | Typ.Revoke =>
          let s1 ←
            lift (Array.to_slice
              (Array.make 15#usize [
                107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 114#u8, 101#u8,
                118#u8, 111#u8, 107#u8, 101#u8, 47#u8, 118#u8, 49#u8
                ]))
          let (r3, sink4) ← write_bstr sink3 s1
          let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            let (r4, sink5) ← write_bstr sink4 payload
            let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
            match cf4 with
            | core.ops.control_flow.ControlFlow.Continue _ =>
              let written_len ← SliceSink.impl.len sink5
              if written_len > MAX_MESSAGE_LEN
              then
                ok (core.result.Result.Err (CoseError.Codec
                  CodecError.BufferTooSmall))
              else
                ok (core.result.Result.Ok
                  { buf := sink5.buf, len := written_len })
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                SigStructure CoseError.Insts.CoreConvertFromCodecError residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              SigStructure CoseError.Insts.CoreConvertFromCodecError residual
        | Typ.TrustUpdate =>
          let s1 ←
            lift (Array.to_slice
              (Array.make 21#usize [
                107#u8, 110#u8, 116#u8, 114#u8, 108#u8, 47#u8, 116#u8, 114#u8,
                117#u8, 115#u8, 116#u8, 45#u8, 117#u8, 112#u8, 100#u8, 97#u8,
                116#u8, 101#u8, 47#u8, 118#u8, 49#u8
                ]))
          let (r3, sink4) ← write_bstr sink3 s1
          let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            let (r4, sink5) ← write_bstr sink4 payload
            let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
            match cf4 with
            | core.ops.control_flow.ControlFlow.Continue _ =>
              let written_len ← SliceSink.impl.len sink5
              if written_len > MAX_MESSAGE_LEN
              then
                ok (core.result.Result.Err (CoseError.Codec
                  CodecError.BufferTooSmall))
              else
                ok (core.result.Result.Ok
                  { buf := sink5.buf, len := written_len })
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                SigStructure CoseError.Insts.CoreConvertFromCodecError residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              SigStructure CoseError.Insts.CoreConvertFromCodecError residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          SigStructure CoseError.Insts.CoreConvertFromCodecError residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        SigStructure CoseError.Insts.CoreConvertFromCodecError residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      SigStructure CoseError.Insts.CoreConvertFromCodecError residual

/-- [cose_parse_nopanic::Parsed]
    Source: 'src/lib.rs', lines 811:0-818:1
    Visibility: public -/
structure Parsed where
  kid : Array Std.U8 16#usize
  typ : Typ
  payload : Slice Std.U8

/-- [cose_parse_nopanic::parse_sign1]:
    Source: 'src/lib.rs', lines 837:0-846:1
    Visibility: public -/
def parse_sign1
  (bytes : Slice Std.U8) : Result (core.result.Result Parsed CoseError) := do
  let r ← read_sign1_envelope bytes
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue e =>
    let r1 ← decode_protected_header e.«protected»
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (kid, typ) := val
      let r2 ← build_sig_structure typ e.«protected» e.payload
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        ok (core.result.Result.Ok { kid, typ, payload := e.payload })
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Parsed (core.convert.FromSame CoseError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Parsed (core.convert.FromSame CoseError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Parsed (core.convert.FromSame CoseError) residual

end cose_parse_nopanic
